### ISSUE TITLE
Testing (Jest)

### ISSUE THREAD

**Issue by MDShields7** [MDShields7/sumo-rank#13]
This project is Javascript, and tested with Jest. If you are new to testing and/or Jest, this could be a good fit for you because I have 1 test case per error already as examples. 

Please feel free to add more.  You will see my documentation lays out every error I believe that can and will be thrown.

Easy things to test:
- Basic functionality
- Errors thrown properly
- Edge cases
- Sort methods ( should fail, I don't think I completed throwing errors yet)

Slightly more difficult, but not needed until the errors are all written:
- Sort method, the parameter being an array of objects, with each object containing different rank format types
- Sort method, the parameter being an array of objects with rank separated into properties, see below 
      Example: [ {rank: {name:'Maegashira', number:12, direction:'East'}}, etc... ]
      This method should fail (until it is completed)

Just try to break it too.

**Comment by 2bit-hack** [comment]
Is it okay if I work on this issue?

**Comment by MDShields7** [comment]
Yes, go ahead and take a shot at it. I assigned you to it.

**Comment by 2bit-hack** [comment]
I'm planning on adding more tests for correct inputs (including checking if changing the order of input ranks still works as expected) and tests for the 500 series of errors, to begin with

**Comment by MDShields7** [comment]
Great. The tests file is called 'sumoRank.format.test.js', because I originally planned to have sumoRank.sort methods in a different file called 'sumoRank.sort.test.js'. So you could do 1 of 2 things:
1) Work on splitting those into 2 files as i said above
2) Renaming 'sumoRank.format.test.js' to to 'sumoRank.test.js'
The library is small enough to probably just have 1 test file, but either way is fine with me.

**Comment by 2bit-hack** [comment]
I think I'll split the existing file into `sumoRank.format.test.js` and `sumoRank.sort.test.js` and separate the sort and format test logic.

**Comment by MDShields7** [comment]
Sure, that might make more sense for approaching the 500 series anyways.
Have fun.

**Comment by 2bit-hack** [comment]
Both `sumoRank.format("M two east", "N#D")` and `sumoRank.format("i like turtles", "N#D")` are expected to throw `SR.304` (Non-rank item throw), but instead throw `SR.305` (Multiple instances of rank type)

**Comment by MDShields7** [comment]
I wasn't expecting how well you would misuse sumoRank in those tests. It was kind of funny. Thanks

**Comment by MDShields7** [comment]
> Both `sumoRank.format("M two east", "N#D")` and `sumoRank.format("i like turtles", "N#D")` are expected to throw `SR.304` (Non-rank item throw), but instead throw `SR.305` (Multiple instances of rank type)

Yes, I know... it is because it thinks 'o' in 'two' is Ozeki, therefore two names ranks are present.
Also, the 'e's in 'like' and 'turtles' are considered to be 'east' and therefore 2 names ranks are present.

I don't know if I want a library as small as this to be trying to separate what words are rank or non-rank. Maybe it would be better to combine SR.304 and SR.305? I will think on it. @2bit-hack
